FIND_PATH(SPICE_INCLUDE_DIR NAMES SpiceUsr.h
   PATHS
   ${PROJECT_SOURCE_DIR}/cspice/include
   NO_DEFAULT_PATH
)

FIND_LIBRARY(LIBSPICE
   NAMES
   cspice.a
   PATHS
   ${PROJECT_SOURCE_DIR}/cspice/lib
   NO_DEFAULT_PATH
)

SET (SPICE_LIBRARIES
   ${LIBSPICE}
)

IF(SPICE_INCLUDE_DIR AND SPICE_LIBRARIES)
   SET(SPICE_FOUND TRUE)
ENDIF(SPICE_INCLUDE_DIR AND SPICE_LIBRARIES)

IF(SPICE_FOUND)
   MARK_AS_ADVANCED(SPICE_INCLUDE_DIR SPICE_LIBRARIES)
ENDIF(SPICE_FOUND)
